# Header
menu:
  Home: /
  Archives: /archives


# Favicon
favicon:

# Hero - Please specify width and height for structured data
hero:
  url:
  width:
  height:


# Profile
profile:
  gravatar:
  social:
    github:
    facebook:
    linkedin:
    instagram:
    twitter:
    flickr:
    rss:


# Site Verification
site_verification:
  enable: true
  google:
  naver:
  bing:


# Analytics
analytics:
  google:
  naver:


# web fonts
webfonts:
  uses: ['Noto Sans KR', 'Font Awesome']
  extraFonts:
  #  - family:
  #    url:


# Extenreal Links
links:
  #  - name:
  #    url:


# Comments
liveRe:
  uid:

disqus:
  shortname:
