# Header
menu:
  Home: /
  Archives: /archives

# Images
favicon: /images/favicon.png

# Profile
profile:
  gravatar:
  social:
    github:
    facebook:
    linkedin:
    instagram:
    twitter:
    flickr:


# Site Verification
google_site_verification:
naver-site-verification:

# Analytics
analytics:
  google:
  naver:

# web fonts
webfonts:
  uses: ['Noto Sans KR', 'Font Awesome']
  extraFonts:
  #  - family:
  #    url:

# Extenreal Links

links:
#  - name:
#    url: